POST http://localhost:5173/api/messages
Content-Type: application/json

{
  "text": "Hi, I'm Noah - how can I help you today?",
  "clientId": "PLACEHOLDER"
}

POST http://localhost:5173/api/messages
Content-Type: application/json

{
  "text": "Sure, I can help with that! What's the client's Member ID?",
  "clientId": "PLACEHOLDER"
}

POST http://localhost:5173/api/messages
Content-Type: application/json

{
  "text": "Great! What's the client's date of birth?",
  "clientId": "PLACEHOLDER"
}

POST http://localhost:5173/api/messages
Content-Type: application/json

{
  "text": "Looking them up....seems like they are in-network and they have a $1,000 deductible, they contributed $540 so far. Additionally, they have a $40 copay for each session and a coinsurance of 20%. The out of pocket maximum is $200. How can I help you further?",
  "clientId": "PLACEHOLDER"
}

POST http://localhost:5173/api/messages
Content-Type: application/json

{
  "text": "Yes, that's correct.",
  "clientId": "PLACEHOLDER"
}

POST http://localhost:5173/api/messages
Content-Type: application/json

{
  "text": "Awesome! I'm glad I could help.",
  "clientId": "PLACEHOLDER"
}
