POST http://localhost:5173/api/messages
Content-Type: application/json

{
  "text": "Hi, I'm Abigail - how can I help you today?",
  "clientId": "PLACEHOLDER"
}

POST http://localhost:5173/api/messages
Content-Type: application/json

{
  "text": "Sure, I can help with that! What's the client's Member ID and date of birth?",
  "clientId": "PLACEHOLDER"
}

POST http://localhost:5173/api/messages
Content-Type: application/json

{
  "text": "Alright, I'm checking on that now. It seems this client's policy has a limit of 24 visits per year. After that they will pay the full session fee.",
  "clientId": "PLACEHOLDER"
}
